csa:
    kb_path: /home/meng/Workspace/funzler_py/csa/CSA_Example.xlsx
    kb_sheet: KB (preprocessing)
    csa_range: # C4:L600
        columns: C:L # columns where data are
        header_row_index: 2 # row of headers, 0-indexed
    ev_range: # U4:U30
        columns: U
        header_row_index: 2
    bouc_range: # T4:T600
        columns: T
        header_row_index: 2
    skip_rows: [0, 1] # discarded rows
input:
    obs_mode: manual # manual / automated
    meas_mode: manual # manual / automated
params:
    plot_ctrl: False
    n_showhypo: 1
    n_advisemeas: 10
    thres_plausi: 0.7999999
    thres_showhypo: 0.7999999
    thres_find_double_bouc: 0.7999999
    thres_boucmeas_advice: 0.7999999

# only for development, not transfered kbinit.m codes are
# line 20 - line 24
# line 26 - line 35
